### ISSUE TITLE
Crashes Safari on 15.4 Beta 1

### ISSUE THREAD

**Issue by httpjamesm** [smmr-software/privacy-redirect-safari#20]
Privacy Redirect makes Safari on iOS 15.4 crash instantly on launch and when managing its settings through iOS Safari Settings. 

How to reproduce:
- Update to 15.4 B1
- Enable Privacy Redirect Extension
- Try to launch

**Comment by httpjamesm** [comment]
Reinstalling the app seemed to work.

**Comment by FIGBERT** [comment]
The iOS app is about to receive a major update soon which should fix a lot of the problems people are experiencing. Apple has been blocking all our updates since version 1.0.0, but we've addressed all their complaints and submitted an update to version 1.1.3. We've been waiting for review for four days now...

Regardless, I'm glad your crash resolved itself.

**Comment by httpjamesm** [comment]
I've updated but the issue persists. It seems to work fine until I close out Safari, and then it starts to crash it.

**Comment by pettersillander** [comment]
Same problem here. 

I just installed version 1.1.3 but issue persists still.

**Comment by arthurlt** [comment]
Issue appears to be persisting on beta2 with app version 1.1.3.

**Comment by FIGBERT** [comment]
I've just looked through the release notes for the iOS 15.4 betas to see if there were any deprecations that would affect our extension - doesn't seem to be anything obvious. I'll investigate further on my own devices.

**Comment by arthurlt** [comment]
Appears to have the same issue on iOS 15.4 beta 5.

**Comment by FIGBERT** [comment]
OK: I've got a device running the most recent beta now (iPhone 12 mini, iOS 15.4 Beta 5).

The crash seems to be caused by an error in Apple's `manifest.json` parser, which fails on our currently very long list of sites to access (1353 sites).

One way we could work around this is by simply requesting access to *every* site via `<all_urls>` – I've tested this on my device and it fixes the issue. However, we have explicitly avoided requesting `<all_urls>` in our development thus far.

I've submitted feedback to Apple about this bug (FB9945121), and will post further updates here. In the meantime, I welcome any and all feedback.

**Comment by httpjamesm** [comment]
The newest update seems to have fixed crashes on 15.4 RC.
